### ISSUE TITLE
Fix typo on website (Acuia --> Acquia)

### ISSUE THREAD

**Issue by fureigh** [georgetown-university/druml#45]
_I came here to submit a pull request, but this repo appears to be strictly for druml itself. Thanks for your work!_

On http://www.usedruml.com, change `Acuia` to `Acquia`.

Current:
> Copies DB and files of edited sites from stage environment to production in Acuia Cloud. 

Proposed:
> Copies DB and files of edited sites from stage environment to production in Acquia Cloud.

**Comment by ghost** [comment]
@fureigh thank you, good catch! Fixed.
